### ISSUE TITLE
event to lock cluster when zooming (prevent update)

### ISSUE THREAD

**Issue by henrikmaa** [oliverroick/Leaflet.Deflate#109]
**Describe the solution you'd like**
A function to freeze the deflate at a certain zoom level. Preventing any updates to the deflating/clustering until you unlock the layers again. 

**Describe alternatives you've considered**
L.markercluster has a sub plugin for this: https://github.com/ghybs/Leaflet.MarkerCluster.Freezable
I could not make it work because I could not get access to L.markerClusterGroup

**Additional context**
https://ghybs.github.io/Leaflet.MarkerCluster.Freezable/examples/mcg-freezable.html?leaflet=1.3.1&leaflet.markercluster=1.3.0&leaflet.markercluster.freezable=1.0.0
freezeAtZoom()

**Comment by oliverroick** [comment]
Hi @henrikmaa,

I've just published a beta that should make `Leaflet.Deflate` work with `Leaflet.MarkerCluster.Freezable`. It introduces layer injection, that means, you can now inject the layer used to display deflated features on the map, which allows you to control that layer outside of `L.deflate`. 

You can install the beta using `npm install Leaflet.Deflate@next`

There is an [example for markercluster.freezable](https://github.com/oliverroick/Leaflet.Deflate/blob/layer-injection/example/markercluster-freezable.html) in the branch I'm working on.

You basically have to instantiate a `L.markerClusterGroup` and then pass it as the `markerLayer` option into `L.deflate`:

```js
var map = L.map("map").setView([51.550406, -0.140765], 16);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var layer = L.markerClusterGroup();
var features = L.deflate({minSize: 20, markerLayer: layer});
features.addTo(map);

// add all your features

layer.freezeAtZoom(15);
```

Let me know how this works for you. If this is ok, I can make a full release soon.

**Comment by oliverroick** [comment]
The changes have been release with 1.4.0. Closing the ticket.
