### ISSUE TITLE
GeoJson in FeatureGroup don't deflate

### ISSUE THREAD

**Issue by blackninja65** [oliverroick/Leaflet.Deflate#11]
Hi,

I can not success in deflating geojson in a featureGroup

Is there a way to accomplish ?

Thanks for your plugin !

**Comment by oliverroick** [comment]
There is [an example](https://github.com/oliverroick/Leaflet.Deflate/blob/master/example/index.html) you can follow. 

If you still can't get it to work, I would need a little more context (an excerpt of your code, for instance) to able to help you.

**Comment by blackninja65** [comment]
Thanks for your quick answer !

I take exactly your example.
I have only added a featureGroup to the map :
`var featureGroup = L.featureGroup().addTo(map)`

Load the example JSON in this featureGroup : 
`L.geoJson(json).addTo(featureGroup);`

And deflate this featureGroup :
`L.Deflate({minSize: 20, featureGroup: featureGroup}).addTo(map);`

the whole code :        [https://jsfiddle.net/7mc82dpk/](https://jsfiddle.net/7mc82dpk/)

```
var map = L.map("map").setView([51.505, -0.09], 7);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var json = { ... your example json ... };

var featureGroup = L.featureGroup().addTo(map);

L.Deflate({minSize: 20, featureGroup: featureGroup}).addTo(map);

L.geoJson(json).addTo(featureGroup);
```
Thank you !

**Comment by oliverroick** [comment]
So, the problem is you're adding a GeoJSON layer to a feature group, which means you add a feature group to a feature group. That isn't supported at the moment. 

Is there a reason why you add the GeoJSON layer to a feature group, do you want to add additional features to the feature group, for instance? If it's just the GeoJSON you want to deflate, then you can add that layer directly to the map.

This works, for instance:

```javascript
var map = L.map("map").setView([51.505, -0.09], 7);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var json = { // your json
}

L.Deflate({minSize: 20).addTo(map);

L.geoJson(json).addTo(map);

```

**Comment by blackninja65** [comment]
Ok thanks !
You remind me that L.geoJson extends L.featureGroup ...

In my app, I first tested with simple layers in a featureGroup (allow to show/hide all the group)
and next fill it with geojson.

All works fine with geojson directly in the map.

Thanks a lot !!!

**Comment by oliverroick** [comment]
No worries!
