### ISSUE TITLE
Marker not shown

### ISSUE THREAD

**Issue by mocnik-science** [oliverroick/Leaflet.Deflate#153]
I have tested `simple.html` in several browsers.  The geometries are shown as expected, but the markers are not shown when the geometry is hidden at smaller scales.

Any idea?  Thanks in advance!

**Comment by oliverroick** [comment]
Hi @mocnik-science,
this is a bug. Thanks for spotting this. I'll get a fix ready.

**Comment by mocnik-science** [comment]
Hi Oliver,
Thanks for your swift reply, and thanks for fixing the bug!

**Comment by oliverroick** [comment]
This should be fixed in 1.4.2. Feel free to re-open if the problem persists.

**Comment by mocnik-science** [comment]
Thank you very much for your swift reaction.  I can confirm that it works again.
