### ISSUE TITLE
Deflate for featureGroup from JSON doesn't work

### ISSUE THREAD

**Issue by petrovnn** [oliverroick/Leaflet.Deflate#16]
I want the L.Deflate plug-in to be applied only to red buildings.

Created **L.featureGroup()** and put red buildings there, but Deflate does not work.

This code works for all buildings:

    L.Deflate({minSize: 10).addTo(map);

If I try to put red buildings in this layer, Deflate does not work:

    L.Deflate({minSize: 10, featureGroup: group_red}).AddTo(map);

how can I do this and is it possible, is it at all?

here JSfiddle, demonstrating the problem (uncomment line 15)

https://jsfiddle.net/petrovnn/65y1ed8w/

**Comment by oliverroick** [comment]
Hi @petrovnn,

`L.geoJson`extends `L.FeatureGroup`, so you're trying to add a feature group to a feature group, which is unfortunately not supported at this point in Leaflet.Deflate.

There are two things you can do:

1. You could create `L.Polygon`objects from your geometries and add those to `group_red`.
2. There is a highly experimental branch [`0.4-rewrite`](https://github.com/oliverroick/Leaflet.Deflate/tree/0.4-rewrite), which is trying to solve these problems by treating `L.Deflate` like a layer. I'm assuming that it works, but I can't guarantee. It's unfinished work, not tested yet; so use with caution!

Hope it helps!

**Comment by oliverroick** [comment]
Hi @petrovnn,

I made some progress with the upcoming rewrite now. [Here's an example](https://github.com/oliverroick/Leaflet.Deflate/blob/dev-1.0-docs/example/geojson-two-layers.html) how you can apply Leaflet.Deflate to only one GeoJSON layer. It works with the src in branch `dev-1.0`.

Could you have a look and let me know if that works for you? Helping me test this will really help me towards getting the next release out. 

Many thanks!

**Comment by petrovnn** [comment]
Hi @oliverroick!

Thank you for realy great work!

I've tested your new version and it definitely works like I wanted.

However, I could not bind the tooltip to the markers (blue polygons).

Unfortunately I do not know how to pass options to set the marker style, so the marker style in the Deflate plugin file:
```
var blue_square = L.Icon.extend({
	options: {
		iconSize:     [16, 16],
		iconAnchor:   [8, 8],
		popupAnchor:  [0, 0]
	}
});
var blue_square_obj = new blue_square({iconUrl: 'https://msys.pro/test/dot_middle_blue.png'});
var marker = L.marker(layer.getBounds().getCenter(), {icon: blue_square_obj});
```
in this file: https://msys.pro/test/L.Deflate_dev_1.0.js 

Here is updated Fiddle: 
https://jsfiddle.net/petrovnn/65y1ed8w/10/

**Comment by oliverroick** [comment]
Instead of changing the Leaflet.Deflate code itself to create custom markers; I would recommend using custom markers. Here's [a fork of your fiddle](https://jsfiddle.net/oliverroick/e8vhcsph/1/) showing how to do that; or an example if you want to [use a function to create your icon](https://github.com/oliverroick/Leaflet.Deflate/blob/dev-1.0-docs/example/custom-marker-function.html).

I'm going to look into support for tooltips now; that's something I haven't considered. The binding is not passed to the marker, that's why it's not working.

**Comment by petrovnn** [comment]
> The binding is not passed to the marker, that's why it's not working.

Sadly.

Popups for markers/polygons is also a binding?
And it does not work now?

**Comment by oliverroick** [comment]
Popups work for normal layers but not for GeoJSON layers.

I'm just looking into that, it's not difficult to solve. Expect a solution by the end of the week.

**Comment by petrovnn** [comment]
thanks!

**Comment by oliverroick** [comment]
👍  No worries!
