### ISSUE TITLE
Compatibility with L.PolylineDecorator

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [oliverroick/Leaflet.Deflate#31]
Hi,

thank you so far for your great work :)

I tried to use Deflate now with a set of FeatureGroups that each contain 2 Polylines and one PolylineDecorator. If i add that group to the Deflate Layer, the PolyLines are visible and deflated, but the PolylineDecorator isn't shown up anymore. I figured out that, as PolylineDecorator itsself is extended from FeatureGroup, deflate tries to dig into it in addLayer() - is there any reason why all layers are handled flat style instead of just holding the group?

Have you any advice what needs to be done to make it compatible? I may work on L.PolylineDecorator if that is needed as well.

Thanks.

**Comment by oliverroick** [comment]
Hi @it-solutions-zehaczek,

> is there any reason why all layers are handled flat style instead of just holding the group?

For every zoom event, we have to check all layers if they need inflating or deflating; doing that over a flat list just seemed the right thing to do. 

I'm not too familiar with `PolylineDecorator`, and I just had a brief look at the code. It looks like `FeatureGroup` is used to make patterns possible, so if you have a dashed line, each dash is a separate layer. If that's the case (correct me if my understanding is wrong, I don't know for sure), then handling these cases is quite difficult. Under normal circumstances, I'd say a `FeatureGroup` is a group of individual features, so we can handle each feature when deflating. If in `PolylineDecorator` a `FeatureGroup` actually only represents one feature then we need to deflate the whole `FeatureGroup`, which certainly can be done but we'd somehow have to differentiate between `FeatureGroup`s that are only one feature and actual groups of features so we can handle the cases differently. 

There's probably a way to make that happen; I need to think about it a little. Unfortunately (for you at least), I'll be offline from next week until mid-January, so I won't be able to look into it anytime soon. Unless you have an idea, I'm happy to take PRs ;)

**Comment by it-solutions-zehaczek** [comment]
I thought the getBounds() interface of a FeatureGroup is recursive. 

```
	// @method getBounds(): LatLngBounds
	// Returns the LatLngBounds of the Feature Group (created from bounds and coordinates of its children).
	getBounds: function () {
		var bounds = new LatLngBounds();

		for (var id in this._layers) {
			var layer = this._layers[id];
			bounds.extend(layer.getBounds ? layer.getBounds() : layer.getLatLng());
		}
		return bounds;
	}

```

That means for inflate/deflate checks, it could be enough to call that on the top level groups (the level the layers were added onto the Deflate layer) and inflate/deflate the whole group based on that bounds diameter/size then. My Polylines on my groups will report their bounds properly as well as single latLng-objects do (see code above). The Decorator master is incompatible with this interface (has neither getBounds or getLatLng implemented) but that is sth. i can contribute we don't need to take care here.

I am also out for a while so have a nice time, may i'll give it a try by myself next year :)

**Comment by oliverroick** [comment]
Hi @it-solutions-zehaczek,

I did a bit of work over the weekend, which, I believe, gets us closer to resolving this issue.

Would you be able to put together a quick example for this, may on JSFiddle, so I can dig a bit deeper into the issue? That would be really helpful!

Thanks, Oliver.
