### ISSUE TITLE
getting Leaflet.Deflate to work

### ISSUE THREAD

**Issue by udos** [oliverroick/Leaflet.Deflate#33]
sorry about this. I tried to get Leaflet.Deflate to work but I'm struggling...

chapter [Usage](https://github.com/oliverroick/Leaflet.Deflate#usage) says to use
`<script src="https://unpkg.com/Leaflet.Deflate@0.4.0/dist/L.Deflate.js"></script>`
the issue is that version 0.4.0 is not available on unpkg.com. -> when navigating to `unpkg.com/Leaflet.Deflate@0.4.0/dist/L.Deflate.js` directly it says 
> Cannot find package Leaflet.Deflate@0.4.0

this might be due to the outdated [dist](https://github.com/oliverroick/Leaflet.Deflate/tree/master/dist) directory (last commit "a year ago")

could you please take a look at this?

thanks, udo

ps: it would be great to update [npmjs.com/package/Leaflet.Deflate](https://www.npmjs.com/package/Leaflet.Deflate) as well :)

**Comment by oliverroick** [comment]
> sorry about this

No worries; that's a fault on my end. The docs on `master` aren't up-to-date. I'll fix that next week. I'm sorry that it's so confusing.

If you want the latest stable version, that would be `0.3`. The correct unpkg link would be `https://unpkg.com/Leaflet.Deflate@0.3.0/dist/L.Deflate.js`. You can find the corresponding docs on the [`maintenance/0.3` branch](https://github.com/oliverroick/Leaflet.Deflate/tree/maintenance/0.3). 

I'm planning to get the new version out over the next week. It will change the API a fair bit, so if you can wait until the end of the week, I'd recommend you do that. On the other hand, switching from 0.3 to the new 1.0 won't be that difficult.

**Comment by oliverroick** [comment]
The README is updated now and pre-release 1.0.0-alpha.2 is now available. Sorry for the delay!
