### ISSUE TITLE
Incompatibility with leaflet-realtime.

### ISSUE THREAD

**Issue by Meekelis** [oliverroick/Leaflet.Deflate#46]
Thanks for a brilliant plugin.

Markers from a geoJSON string going through [L.realtime()](https://github.com/perliedman/leaflet-realtime) seem to end up causing an undefined object. I'm using the 0.3 branch for better circle support.

```
[Error] TypeError: undefined is not an object (evaluating 't.lat')
	project (leaflet.js:5:24157)
	latLngToPoint (leaflet.js:5:22804)
	isCollapsed (L.Deflate.js:9)
	getZoomThreshold (L.Deflate.js:20)
	layeradd (L.Deflate.js:41)
	fire (leaflet.js:5:16626)
	_layerAdd (leaflet.js:5:64842)
	whenReady (leaflet.js:5:44753)
	addLayer (leaflet.js:5:65096)
	addTo (leaflet.js:5:64049)
	Global Code (poi:326)
```

The issue does not occur if a featureGroup is used to exclude the realtime markers. It may be more convenient to have L.Deflate ignore these leaflet-realtime features it doesn't support, but this issue can be closed as the workaround is so intuitive.

**Comment by oliverroick** [comment]
Hi @Meekelis,

thanks for your feedback. I don't fully understand the issue here, as I don't have any experience with leaflet-realtime. Could you provide me a quick example, maybe in JSFiddle, so I can dig a bit into this. 

Thanks, Oliver.

**Comment by oliverroick** [comment]
I will be discontinuing the `0.3` branch soon, hence I won't get around to look into this. If you encounter the same issue with `master`, feel free to re-open the ticket.
