### ISSUE TITLE
Layer level

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [oliverroick/Leaflet.Deflate#5]
Hi,

i want this plugin on layer level with a predefined collapse marker on feature level. Have you any suggestion on how to achieve this?

Chris

**Comment by oliverroick** [comment]
As for applying the plugin to a selected layer only, this is something I have been working on recently. It's almost ready, "just" need to do some clean-up, tests and documentation. Hope to get that done early next week, but I can't make any promises. 

For custom markers, this does not sound like something too complicated. The marker for each path is set [here](https://github.com/oliverroick/Leaflet.Deflate/blob/master/src/L.Map.Deflate.js#L41). The way to go is probably to provide a custom marker via the `options` and then applying that when the marker is created. Do you think this is something you could contribute?

**Comment by Hekkenberg** [comment]
I would really appriciate it if this would become a features as i am currently right stuck on that same problems, i wish to replace the default marker with a custom one, as I described on stackoverflow.com (http://stackoverflow.com/questions/40489828/leaflet-js-leaflet-deflate-changing-default-marker-icon-to-custom-icon/40547412#40547412)

The idea of being able to customize the markers would be an awesome addition to this already amazing plugin. Thanks for your consideration.

**Comment by oliverroick** [comment]
Custom markers will be supported with the new version (currently on branch `1.0-dev`).

**Comment by oliverroick** [comment]
With the rewrite (source is now in `master`) coming up, custom markers, as well as layer-level deflation, will be supported. 

Closing the ticket, feel free to re-open if there are bugs.
