### ISSUE TITLE
feature request - option to not cluster single objects

### ISSUE THREAD

**Issue by udos** [oliverroick/Leaflet.Deflate#51]
I am using Leaflet.Deflate to cluster GeoJSON objects. it would be really nice if Leaflet.Deflate could be configured not to cluster single objects to prevent something like this:
![image](https://user-images.githubusercontent.com/141107/43655932-ddc6325c-9750-11e8-8cf2-e70108c7c30d.png)
note: in above example 1 GeoJSON object is clustered and displayed as 1 marker... it would be nice if it would not do this... the cluster of 2 is perfectly fine.

not sure if my point has passed. available for clarifications :)

maybe this is already possible, but I was unable to figure out how...

**Comment by oliverroick** [comment]
Hi @udos,

we're using [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster) to enable clustering of markers. It has a `maxClusterRadius` option, which defines the area a cluster can cover. You can pass it to the `markerClusterOptions` option when defining the `L.Deflate` layer. You can play around with that to make it fit your data set. 

It might be possible, though, that, no matter what `maxClusterRadius` you choose, there might always be markers which are too far from other neighboring markers to form a cluster. 

If this doesn't help, I'd recommend filing the request with Leaflet.markercluster, they might be able to help you.

**Comment by udos** [comment]
thank you very much oliver! I had a feeling that this might be driven by [ Leaflet.markercluster]( https://github.com/Leaflet/Leaflet.markercluster) :| sorry about this

**Comment by udos** [comment]
@oliverroick, I somehow can't get _ markerClusterOptions_ to work. I tried the following simple setting to check if it works:

```
...
let features = L.deflate(
    {
        minSize: 20,
        markerCluster: true,
        markerClusterOptions: {
            showCoverageOnHover: false
        }
    }
);
features.addTo(map);
...
```

unfortunately hovering is still showing area coverage...

am I applying _ markerClusterOptions_ correctly?

**Comment by udos** [comment]
@oliverroick, I added a jsfiddle to previous question. could you please take look?
note: or should I open a dedicated issue?

**Comment by udos** [comment]
I'm stuck trying your suggestion https://github.com/oliverroick/Leaflet.Deflate/issues/51#issuecomment-410624775 due to issue #53 :| it would be really helpful if you could take a look.
note: there is a jsfiddle link at the end of the issue which makes it pretty easy for you to figure out if the error is on my end (configuration) or an issue in _Leaflet.Deaflate_...
