### ISSUE TITLE
Leaflet.Deflate with Leaflet.markercluster does not show coverage on hover

### ISSUE THREAD

**Issue by udos** [oliverroick/Leaflet.Deflate#52]
for some reason, cluster coverage is not showing on hover. I tried to get an answer on stackoverflow without success (so far).

the issue is described in

- https://stackoverflow.com/q/51781142/420953<br>note: there is also a jsfiddle here -> https://jsfiddle.net/udos/q426p30n/3/

probably easy to spot for someone familiar with Leaflet.Deflate/Leaflet.markercluster

thanks

**Comment by udos** [comment]
embarassed -> figured it out -> https://stackoverflow.com/a/51827247/420953

sorry about this!

**Comment by oliverroick** [comment]
No need to be embarrassed; coding is hard, we've all been there.

Glad you figured it out.
