### ISSUE TITLE
markerClusterOptions are not applied

### ISSUE THREAD

**Issue by udos** [oliverroick/Leaflet.Deflate#53]
based on suggestion https://github.com/oliverroick/Leaflet.Deflate/issues/51#issuecomment-410624775 I'm trying to enable _**[markerClusterOptions](https://github.com/oliverroick/Leaflet.Deflate#options)**_ in Leaflet.Defalte as following (for simplicity I picked a simple setting):

```
...
let deflate_features = L.deflate(
    {
        minSize: 40,
        markerCluster: true,
        markerClusterOptions: {
            showCoverageOnHover: false
        }
    }
);
deflate_features.addTo(map);
...
```

unfortunately hovering is still showing area coverage even though option _**showCoverageOnHover: false**_ should disable it...

am I applying _**markerClusterOptions**_ correctly?

**note:** I added a jsfiddle to make it easier to check/analyze what's wrong-> https://jsfiddle.net/Lo2eq09v/2/

thanks for having a look

**Comment by udos** [comment]
ok. after some digging I found out that when you are installing the library with
```
npm install Leaflet.Deflate@1.0.0-alpha.2
```
an old version is installed...

in:
- node_modules/Leaflet.Deflate/src/L.Deflate.js
- node_modules/Leaflet.Deflate/dist/L.Deflate.js

the following code is available:
```
L.Deflate = L.FeatureGroup.extend({
    options: {
        minSize: 10,
        markerCluster: false,
        markerOptions: {}
    },
    ...
```

which looks outdated compared to the current code in https://github.com/oliverroick/Leaflet.Deflate/blob/master/src/L.Deflate.js:
```
L.Deflate = L.FeatureGroup.extend({
    options: {
        minSize: 10,
        markerCluster: false,
        markerOptions: {},
        markerClusterOptions: {}
    },
    ...
```
if I manually replace the code, _**markerClusterOptions**_ are applied correctly :)

a quick fix of the npm repository would be nice ;)

**Comment by oliverroick** [comment]
Hi @udos,

I'm really sorry about that. Just published `1.0.0-alpha.3`, which hopefully should work for you. I'm also sorry about the lack of responsiveness from my end.

**Comment by udos** [comment]
no worries! hard to spot on your side. I will take a look when I‘m back from a short trip in the mountains.

**Comment by udos** [comment]
works like a charm! thanks!
