### ISSUE TITLE
Deflate with ui-leaflet

### ISSUE THREAD

**Issue by TSilviu** [oliverroick/Leaflet.Deflate#6]
Hello!

Nice work!
I was wondering if there is any way of integrating this with ui-leaflet: http://angular-ui.github.io/ui-leaflet/#!/

Thanks,
Silviu

**Comment by oliverroick** [comment]
Hi Silviu,

I guess it is possible to integrate Leaflet.Deflate. From looking at the examples, I guess creating a custom controller is the way to go. I can't tell for sure, though; I'm not exactly an Angular expert. Do you know of any examples of integrations with other Leaflet extensions?

**Comment by TSilviu** [comment]
Thanks! I may have a look into how to do that. I will let you know if I have any success.

I've tried integrating ui-leaflet with Proj4Leaflet before and did not have an easy time. I ended up using ui-leaflet, Leaflet and proj4js separate and made the links myself which worked fine so far :D. The reason I needed this was because I had to do some CRS transformations on some GeoJSON.

**Comment by oliverroick** [comment]
Hey, not sure if this is still ongoing. Closing the ticket for the time being. Feel free to re-open if necessary.
