### ISSUE TITLE
markerOptions not called on points

### ISSUE THREAD

**Issue by dumar** [oliverroick/Leaflet.Deflate#93]
Hello,
Thank you for this plugin, it is something I was looking for.
I have problem with setting custom icons using _markerOptions_. I have mixed points and polygons features in one geojson.  _markerOptions_ set desired icon correctly only for polygons, while points still have the default icon. I am not sure if this is feature or bug, but it would be convenient to be able to modify icons of any feature type.  If I understand correctly, _markerOptions_ is called only on the deflated features. If this is intended, what would be the best way to set icon of not deflated features within same features group.

**Comment by oliverroick** [comment]
Hi @dumar,

you're right, Leaflet.Deflate's markerOptions only specify options for deflated features. You should be able to specify the default style in your GeoJSON layer.

Something like:

```js
var features = L.deflate({
  minSize: 20
  markerOptions: {
    // for deflated features
  }
});
features.addTo(map);

L.geoJson(json, {style: {color: '#0000FF'}}).addTo(features);
```

The `style` option for the geoJSON layer defines the default style. The options you can use are [documented here](https://leafletjs.com/reference-1.6.0.html#path-option). I think, you can specify a marker though.
